location / {
            root   /dist;
            index  index.html index.htm;
        }

        #error_page  404              /404.html;

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }

        location /media/ {
            alias /backend/media/;
            autoindex on;
        }

        location ^~ /api/ {
                # 负载均衡
            proxy_pass http://localhost:6000/;
            proxy_set_header Host $host;
        }