version: "3"
services:
  yinbao:
    container_name: fast
    build:
      context: .
      dockerfile: env_dockerfile
    image: fast

  backend:
    container_name: fastbackend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5500:5500"
    depends_on:
      - fast

  mysql:
    image: mysql:latest
    container_name: fastmysql
    environment:
      - MYSQL_ROOT_PASSWORD=fast_ZC67!0*
      - MYSQL_DATABASE=fast
      - TZ=Asia/Shanghai
    volumes:
      - /fast/mysql/log:/var/log/mysql
      - /fast/mysql/data:/var/lib/mysql
      - /fast/mysql/conf.d:/etc/mysql/conf.d
    ports:
      - "3306:3306"
    restart: always
